### PR TITLE
"Fixed Import Errors With Keras

### PR DESCRIPTION
**Pull request by ghost**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

"Fixed Error With Keras and other libraries like Tensorflow Hub's Import: ImportError: cannot import name '__version__' from 'keras' (/usr/local/lib/python3.7/dist-packages/keras/__init__.py)"

### CODE REVIEW

**Comment by gikf** [comment]
Could you write something more about this change? Where are you seeing the errors and how to reproduce them? I'm not having any issues when importing modules from starting code.

**Comment by ghost** [comment]
> 
> 
> Could you write something more about this change? Where are you seeing the errors and how to reproduce them? I'm not having any issues when importing modules from starting code.

There is no error when trying to import the modules. However, when you try to use tools like Tokenizer or Tensorflow Hub, it is giving a vague error that it cannot import name 'version' from 'keras' (/usr/local/lib/python3.7/dist-packages/keras/init.py)"

I took a fair amount of time understanding it and it was an issue with the importing on TensorFlow and the mismatching of libraries!

**Comment by gikf** [comment]
If I understand this correctly, issue appears only when trying to use some additional tool or library? I'd consider if something like this requires fixing, if problem doesn't occur during typical solving of the project.

**Comment by ghost** [comment]
> 
> 
> If I understand this correctly, issue appears only when trying to use some additional tool or library? I'd consider if something like this requires fixing, if problem doesn't occur during typical solving of the project.

Actually, it isn't an additional library. Keras is a part of Tensorflow and is required to help code this project. There is a compatibility error between the version of Keras and the version of Tensorflow due to which Keras and some other libraries aren't running as expected. I could code the project after fixing this error.

**Comment by gikf** [comment]
I might be confused then. In what circumstances the issue appears? Could you provide steps to reproduce it and/or example code?

**Comment by ghost** [comment]
Sure. I'll provide you with my code. You can change the import code to the default one and try running the project!

Colab: https://colab.research.google.com/drive/1nURddS4n_fMHX74dpeaRbxlYL8pQvXEZ?usp=sharing

Thanks!

PS: If you don't get any error, the problem should have been solved by TensorFlow already.

**Comment by gikf** [comment]
Thanks, I've changed the imports to the original version from boilerplate and haven't got any issues with running the code. I guess whatever was the problem was fixed. Because of that it seems this PR can be closed.

**Pull request closed without merging**
