### PR TITLE
chore: remove instructions

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Comment by ojeytonwilliams** [comment]
This looks good, but I'm a little out of the loop. Where are the instructions being hosted instead?

**Comment by gikf** [comment]
@ojeytonwilliams they are at the project page, for this one - https://www.freecodecamp.org/learn/machine-learning-with-python/machine-learning-with-python-projects/neural-network-sms-text-classifier

**Comment by ojeytonwilliams** [comment]
That should have been the obvious place to look!  Thanks :)

**Pull request merged**
